[
build
]
  functions = "netlify/functions"

[
functions
]
  node_bundler = "esbuild"
  included_files = ["node_modules/axios/**"]

[[
redirects
]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[
functions."generate-hooks"
]
  timeout = 30
